/**
 * GtkApplication flags like `G_APPLICATION_DEFAULT_FLAGS`
 */
export enum GtkApplicationFlags {
  G_APPLICATION_DEFAULT_FLAGS = 0,
  G_APPLICATION_IS_SERVICE = 1,
  G_APPLICATION_IS_LAUNCHER = 2,
  G_APPLICATION_HANDLES_OPEN = 4,
  G_APPLICATION_HANDLES_COMMAND_LINE = 8,
  G_APPLICATION_SEND_ENVIRONMENT = 16,
  G_APPLICATION_NON_UNIQUE = 32,
  G_APPLICATION_CAN_OVERRIDE_APP_ID = 64,
  G_APPLICATION_ALLOW_REPLACEMENT = 128,
  G_APPLICATION_REPLACE = 256,
}
